version: '3.8'

services:
  flaskapp:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    restart: always
    expose:
      - "5000"
    environment:
      - VIRTUAL_HOST=flask-shcoder.pp.ua
      - LETSENCRYPT_HOST=flask-shcoder.pp.ua
      - LETSENCRYPT_EMAIL=navigatordj201@gmail.com
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
